### ISSUE TITLE
adds words with 'x' at the end

### ISSUE THREAD

**Issue by jo-lang** [thundernixon/make-list-of-cool-words#1]
https://github.com/thundernixon/make-list-of-cool-words/blob/1e116bf4379df56a151c06b8a1edcd0d43da2333/make-set-of-cool-words.py#L38

this adds an x to all found words with a comma at the end. 
eg : Santarémx, incontinênciax, adultériosx ...

**Comment by thundernixon** [comment]
Ha, I don't know why or how I added 'x' there, but I think it must have been a random typo. 

I think I fixed it. 

Thanks for pointing it out!
